### ISSUE TITLE
PATCHing the authtype should not be allowed

### ISSUE THREAD

**Issue by werwty** [RedHatInsights/sources-api#196]
Currently if I create an Authentication with authtype `arn`, I would expect that the authtype to be non update-able. 

But the following PATCH request is allowed, and does update my authtype to azure: 
```http -a insights-qa PATCH https://ci.cloud.redhat.com/api/sources/v1.0/authentications/1139 authtype=azure```

**Comment by agrare** [comment]
@slemrmartin can you make authtype a readOnly attribute in the openapi definition?

**Comment by slemrmartin** [comment]
sorry, I didn't notice this issue, will do

**Comment by slemrmartin** [comment]
TPINVTRY-932

**Comment by gmcculloug** [comment]
@slemrmartin @agrare The PR for this change was merged already, but I wanted to point out that we likely only wanted to make it read-only for the PATCH call and other actions like create.  The UI is getting away with this because it makes direct API calls, but anyone using the OpenAPI generated client would fail on a create now that this field is read-only.

cc @zsadeh @lindgrenj6 @syncrou

**Comment by slemrmartin** [comment]
@pkomanek Can you make a follow up PR with the change @gmcculloug described above? (PR is https://github.com/RedHatInsights/sources-api/pull/240)
