### ISSUE TITLE
`partially_available` status and `#check_application_availability` workflow

### ISSUE THREAD

**Issue by pkomanek** [RedHatInsights/sources-api#342]
## Questions:
- Do we want to start using `partially_available` status for source?
  - based on https://issues.redhat.com/browse/RHCLOUD-11552
    - "In case of multiple application for one source (cost management and sub-watch for example), the source object should be updated with the aggregate result of both applications. If one fails and one succeed, there should be a new availability status of "partial" or something similar."
  - Right now it is allowed to use this value for `Source#available_status`, but we do not use it anywhere
    - `... :inclusion => { :in => %w[available partially_available unavailable] } ...`
    - https://github.com/RedHatInsights/sources-api/blob/master/app/models/source.rb#L15
- Do we want to keep calling the worker for `Source#check_application_availability`([here](https://github.com/RedHatInsights/sources-api/blob/master/app/controllers/api/v1/sources_controller.rb#L58-L84))?
  - What about updating the status locally and posting the update message via kafka?
    - It could be something similar to the `AvailabilityStatusListener#process_event`.
    - https://github.com/RedHatInsights/sources-api/blob/master/lib/availability_status_listener.rb#L54-L55
    
## Availability_status check on source workflow(kafka):
1. **Can be created by**:
  1.1. [status change](https://github.com/RedHatInsights/sources-api/blob/2b4d27c1856beff286c3c78c2d0ecf9137a8a2a2/app/models/source.rb#L25) on Source model(in-review)
  1.2 API call ([sources_controller](https://github.com/RedHatInsights/sources-api/blob/master/app/controllers/api/v1/sources_controller.rb#L24))
  1.3 cronjob: available-sources-checker(once per hour at :00 minute)
  1.4 cronjob: unavailable-sources-checker (twice per hour at :15 and :45 minute)  
2. **Creates kafka message**([here](https://github.com/RedHatInsights/sources-api/blob/master/app/controllers/api/v1/sources_controller.rb#L33-L44)) with `"platform.topological-inventory.operations-#{source.source_type.name}"` topic
3. **Consumer of the message**: `topological_inventory-<provider>/lib/topological_inventory/<provider>/operations/worker.rb`
4. **Consumer calls for:** `#availability_check`([here](https://github.com/RedHatInsights/topological_inventory-providers-common/blob/master/lib/topological_inventory/providers/common/operations/source.rb#L43-L57))
  4.1. **connection_status** is `#endpoint_connection_check`([here](https://github.com/RedHatInsights/topological_inventory-providers-common/blob/master/lib/topological_inventory/providers/common/operations/source.rb#L91-L101)). If there is no related endpoint, `#application_connection_check`([here](/blob/master/lib/topological_inventory/providers/common/operations/source.rb#L110-L117)) is used instead
  4.2. **sends kafka message**([here](https://github.com/RedHatInsights/topological_inventory-providers-common/blob/master/lib/topological_inventory/providers/common/operations/source.rb#L128)) for AvailabilityStatusListener in sources-api with **connection_status**
5. **AvailabilityStatusListener sets status** to payload["status"], updates model and raises event about updating the model([here](https://github.com/RedHatInsights/sources-api/blob/master/lib/availability_status_listener.rb#L54-L55))

## AvailabilityStatusConcern
Changing any attribute(except IGNORE_LIST) on Endpoint/Source/Authentication/Application removes(set to nil) `availability_status`, `last_checked_at` and `availability_status_error` attributes.

- This change calls `#remove_availability_status_on_source!` for Endpoint/Authentication/Application
  - sets `availability_status` and `last_checked_at` attributes to nil
  - forces a new availability status check on related source
- This change force `#remove_availability_status_on_resource!` for Authentication
  - forces #`remove_availability_status!` on resource

**Comment by pkomanek** [comment]
@lindgrenj6 @slemrmartin @syncrou What do you think about these questions? Any Ideas or thoughts?

**Comment by lindgrenj6** [comment]
### Do we want to start using partially_available status for source? 
I think this is something we may need to tackle eventually, but as of right now I think it can live in the backlog.

There are basically no instances when a source would have multiple applications or endpoints, it might be coming eventually with superkey but as of right now it just doesn't happen. It also is a UX nightmare as we've found in the past, so I think we should only tackle it when we absolutely need to. 

### Do we want to keep calling the worker for Source#check_application_availability
I am 100% for this, I think this will increase speed + reliability of the application availability operations by a lot, and it makes sense to have this sources specific logic within sources-api and not in topology. This is especially the case since for application-based sources the workers just copy the application status back into the source, why use a dedicated worker when it could just be handled in a mixin or even a callback?

**Comment by slemrmartin** [comment]
@lindgrenj6 can't we have both Cost and SubsWatch apps for one Source?
And if it might come with superkey, it's not as far, I suppose

**Comment by lindgrenj6** [comment]
Yes we can have both on one Source, but that's only really done with
SuperKey.

I guess what I was really trying to say was we should prioritize the
removal of the operations worker stuff over the partially available
piece, it's higher priority IMO. 

We need to get some UX work done for the Partially Available piece
before starting too most likely. That was always the biggest pain point
before.


-- 
Jacob Lindgren

Senior Software Engineer - Insights Platform
Red Hat
***@***.***     M: 402-841-6173

**Comment by slemrmartin** [comment]
about the removal of application-availability-check from operation workers:
they have to be still deployed for endpoint-availability checks and for image names for orchestrator

- if we'll skip sending kafka messages to them, the liveness probe will always fail, at least in production
- if we won't skip sending messages, they still have to query sources-api 2 times/message, but they will do nothing in case of app-check.

**Comment by lindgrenj6** [comment]
> they have to be still deployed for endpoint-availability checks and for image names for orchestrator

Yes, eventually I think we should pull the availability check workers out of operations and over to sources as well. That way we aren't relying on topology for anything.

On the orchestrator side we will probably have to move to a config-map based approach for image SHA's, there is a lot of work to be done on orchestrator still, but there isn't time right now. I want to re-write it to be an actual operator like clowder. 

>if we'll skip sending kafka messages to them, the liveness probe will always fail, at least in production

Yep that's right, I think we should remove the liveness probes in this case since they aren't effective after this change. We could probably leave the satellite one though since that was always the one that was failing (and it's the only one that will get traffic after this change).
